package.json
test/client.spec.ts

- package renamed: `workspace-client` -> `@eclipse-che/workspace-client`
- fixed import in test

rename package, fix test

---

index.d.ts
package-lock.json
src/rest/remote-api.ts

- clean up return types for IRemoteAPI interface
- update package name in package-lock.json
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

clean up return types for IRemoteAPI interface

---

package.json
webpack.config.js

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

fix 'window is not defined' in nodejs

---

package.json
src/index.ts
webpack.config.js

- fix bug when baseUrl is replaced with '/'
- create different bundles to run on nodejs and browser

fix using library on nodejs

---

package.json
src/index.ts
src/json-rpc/json-rpc-api-client.ts
src/json-rpc/json-rpc-client.ts
src/json-rpc/web-socket-client.ts
src/json-rpc/workspace-master-api.ts
src/rest/backend.ts
src/rest/remote-api.ts
src/rest/resources.ts
src/utils/deferred.ts
test/client.spec.ts
typings/moxios.d.ts
typings/types.d.ts
typings/websocket.d.ts

[![Review](http://localhost:8081/factory/resources/factory-review.svg)](http://localhost:8081/f?id=factory0vf4w3ssn9z2bb50)
https://github.com/eclipse/che/issues/10465

Update license to EPL 2.0

---

index.d.ts
src/rest/remote-api.ts
src/rest/resources.ts
typings/types.d.ts

Adds method to fetch a Factory by its ID

Get Factory by ID

---

package.json

Fix failing CI when running tests
https://travis-ci.org/eclipse/che-workspace-client

Fix failing test

---

typings/types.d.ts

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

Add 'Command' items to Runtime

---

src/rest/remote-api.ts
src/rest/resources.ts

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

Add ssh API

---

src/rest/resources.ts

Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

Fix SSH Key Generation. Need to send params in body instead of path params

---

src/index.ts
webpack.config.js

https://github.com/eclipse/che/issues/13574

Add self signed certificate path to the rest config

---

package.json
yarn.lock

Same as https://github.com/eclipse/che-workspace-client/pull/23 but with proper ECA sign off

Upgrade 'axios' to 0.19.0

---

src/rest/remote-api.ts
src/rest/resources.ts

Add getCurrentUser and getOAuthToken methods
Is needed for https://github.com/eclipse/che/issues/14217

Add getCurrentUser and getOAuthToken methods

---

src/index.ts

Rollback commit: https://github.com/eclipse/che-workspace-client/commit/84b960bad5436347e1442038c542a526c449a12e as sometimes in theia browser logs appears error: `self signed certificate in certificate chain`. Need to find better solution to provide mixture public certificates and self-signed.
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

Rollback of support custom public certificates

---

src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts

Fix start the workspace method.
It is part of https://github.com/eclipse/che/issues/17700
Signed-off-by: Oleksii Orel <oorel@redhat.com>

Fix start the workspace method

---

package.json
src/index.ts
src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts
yarn.lock

This PR provides fixes for aligning workspace-client with changes in REST API
fixes  https://github.com/eclipse/che/issues/17700
Signed-off-by: Oleksii Orel <oorel@redhat.com>

Align workspace-client with changes in REST API

---

package.json
yarn.lock

This may be fix eclipse/che#16068

Use axios 0.20.0

---

.github/CODEOWNERS

Make Oleksii Orel and Oleksii Kyrunnyi codeowners

Make Oleksii Orel and Oleksii Kyrunnyi codeowners

---

src/rest/remote-api.ts
test/client.spec.ts

This PR makes it so that we better handle error messages here instead of inside of dashboard-next
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

Change the error message to explain more of what happened

---

src/json-rpc/json-rpc-api-client.ts
src/json-rpc/workspace-master-api.ts

This PR contains:
- Fix unsubcribing to JSON RPC method
- Remove outdated JSON RPC methods

Fix unsubcribing to JSON RPC method

---

.github/workflows/release.yml

Follows up PR I just merged :man_facepalming: 
- changed main to master
- moved release.yaml to .github/workflow folder

Fix release github worklow

---

src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts

Add override params for factory resolver.
It is needed for  https://github.com/eclipse/che/issues/19424
Signed-off-by: Oleksii Orel <oorel@redhat.com>

add override params for factory resolver

---

src/rest/resources.ts

Enhance response provided by https://github.com/eclipse/che/issues/19540
fixes https://github.com/eclipse/che/issues/19925
Change-Id: Ieedc421c4b8529e191e398b367275b02769c15d5
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

feat(factory): Add support for enhanced response from /factory/resolver method

---

src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts

Signed-off-by: Oleksii Orel <oorel@redhat.com>
Add support for namespace provision API.
fixes https://github.com/eclipse/che/issues/20167

Add support for namespace provision API

---

src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts

Add refreshFactoryOauthToken API method

chore: Add refreshFactoryOauthToken API method

---

src/rest/remote-api.ts
src/rest/resources.ts
test/client.spec.ts

Add deleteOAuthToken API method

Add deleteOAuthToken API method

---

.github/workflows/codecov.yml

Fix code-coverage workflow
